// SPDX-FileCopyrightText: 2024 Foundation Devices Inc.
//
// SPDX-License-Identifier: GPL-3.0-or-later

import 'package:envoy/util/console.dart';
import 'package:test/test.dart';
import 'package:foundation_api/foundation_api.dart';
import 'package:foundation_api/src/rust/api/api.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

void main() async {
  test("Test BLE stream", () async {
    const qrCode =
        "UR:ENVELOPE/LFTPSPLRTPSOTANSFGINIEINJKIAJLKOIHJPKKOYTPSOTANSFLJOIDJZKPIHJYJLJLJYISGUIHJPKOINIAIHTPSOTPDAGDGRHPTOVOFETKFDJLPELORNIOOTBBCWKIOYTPSOTANSFLKTIDJZKPIHJYJLJLJYISFXISHSJPHSIAJYIHJPINJKJYINIATPSOTPDAGDFLEOLKIYDRDIFYATMWPYSGHDKGWZDIJKOYTPSOTANSFLIYJKIHJTIEIHJPTPSOTANSGYLFTANSHFHDCXZOJEKOEMMNDISNDPGTWLGSNLZMDWTYNNMWSORNRFBSSGIMPSGAOEVWZOVLOESOYTTANSGRHDCXAXJONEFTVOVOWDGSDSAATEDMBZOTETDRSPFHIDKIFYRKFWGHJZLFPKFEAHYKFXDROYAXTPSOTANSGHHDFZTAHHFLFWFRWEAYIHVDNYNEJPMSHSEMDECPCTDEIHUONLDTDANNFWIDIEDKGSTLFLGYGDQDKOSRFTEYHDWSZENNLUZEAXLDDIYNRSFMEYLFSOHTDEWNDEEEIYAMHNISTIWFPSTBWP";

    await RustLib.init();

    final stream = pairStream(discoveryQr: qrCode);

    stream.listen((data) {
      kPrint(data);
    });

    await Future.delayed(const Duration(seconds: 30));
  });
}
