# SPDX-FileCopyrightText: 2022 Foundation Devices Inc.
#
# SPDX-License-Identifier: GPL-3.0-or-later

analyzer:
  exclude:
    - 'lib/generated'
    - 'lib/business/*.freezed.*'
    - 'integration_test/*'
  plugins:
    - custom_lint
