# SPDX-FileCopyrightText: 2022 Foundation Devices Inc.
#
# SPDX-License-Identifier: GPL-3.0-or-later

include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - 'lib/generated'
    - 'lib/business/*.freezed.*'
  plugins:
    - custom_lint
