# SPDX-FileCopyrightText: 2022 Foundation Devices Inc.
#
# SPDX-License-Identifier: GPL-3.0-or-later

include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - 'lib/generated*'
    - 'lib/business/*.freezed.*'
    - 'packages/ngwallet/**'
    - 'packages/shards/**'
    - 'packages/bluart/**'
    - 'packages/http_tor/**'
    - test/** # TODO: fix and enable tests after ngwallet.dart integration
  plugins:
    - custom_lint
