# SPDX-FileCopyrightText: 2022 Foundation Devices Inc.
#
# SPDX-License-Identifier: GPL-3.0-or-later

include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - 'lib/generated*'
    - 'lib/business/*.freezed.*'
    - 'packages/ngwallet/**'
    - 'packages/backup/**'
    - 'packages/shards/**'
    - 'packages/bluart/**'
    - 'packages/http_tor/**'
    - 'packages/ur/**'
    - 'packages/foundation_api/**'
    - '**/cargokit/**'
    - '**/src/rust/**'
    - '**/frb_generated*'
    - '**/*.freezed.dart'
    - '**/*.g.dart'
    - 'test/*.mocks.dart'
    - 'build/**'
  plugins:
    - custom_lint
