// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../third_party/bc_xid.dart';
import '../third_party/foundation_api/api/backup.dart';
import '../third_party/foundation_api/api/bitcoin.dart';
import '../third_party/foundation_api/api/firmware.dart';
import '../third_party/foundation_api/api/fx.dart';
import '../third_party/foundation_api/api/message.dart';
import '../third_party/foundation_api/api/onboarding.dart';
import '../third_party/foundation_api/api/pairing.dart';
import '../third_party/foundation_api/api/passport.dart';
import '../third_party/foundation_api/api/quantum_link.dart';
import '../third_party/foundation_api/api/raw.dart';
import '../third_party/foundation_api/api/scv.dart';
import '../third_party/foundation_api/api/status.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<EnvoyMasterDechunker> getDecoder() =>
    RustLib.instance.api.crateApiQlGetDecoder();

Future<Uint8List> serializeXid(
        {required QuantumLinkIdentity quantumLinkIdentity}) =>
    RustLib.instance.api
        .crateApiQlSerializeXid(quantumLinkIdentity: quantumLinkIdentity);

Future<Uint8List> serializeXidDocument({required XidDocument xidDocument}) =>
    RustLib.instance.api
        .crateApiQlSerializeXidDocument(xidDocument: xidDocument);

Future<XidDocument> deserializeXid({required List<int> data}) =>
    RustLib.instance.api.crateApiQlDeserializeXid(data: data);

Future<Uint8List> serializeQlIdentity(
        {required QuantumLinkIdentity quantumLinkIdentity}) =>
    RustLib.instance.api.crateApiQlSerializeQlIdentity(
        quantumLinkIdentity: quantumLinkIdentity);

Future<QuantumLinkIdentity> deserializeQlIdentity({required List<int> data}) =>
    RustLib.instance.api.crateApiQlDeserializeQlIdentity(data: data);

Future<DecoderStatus> decode(
        {required List<int> data,
        required EnvoyMasterDechunker decoder,
        required QuantumLinkIdentity quantumLinkIdentity}) =>
    RustLib.instance.api.crateApiQlDecode(
        data: data, decoder: decoder, quantumLinkIdentity: quantumLinkIdentity);

Future<List<QuantumLinkMessage>> splitFwUpdateIntoChunks(
        {required int patchIndex,
        required List<int> patchBytes,
        required BigInt chunkSize}) =>
    RustLib.instance.api.crateApiQlSplitFwUpdateIntoChunks(
        patchIndex: patchIndex, patchBytes: patchBytes, chunkSize: chunkSize);

Future<List<Uint8List>> encode(
        {required EnvoyMessage message,
        required QuantumLinkIdentity sender,
        required XidDocument recipient}) =>
    RustLib.instance.api.crateApiQlEncode(
        message: message, sender: sender, recipient: recipient);

Future<QuantumLinkIdentity> generateQlIdentity() =>
    RustLib.instance.api.crateApiQlGenerateQlIdentity();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<EnvoyMasterDechunker>>
abstract class EnvoyMasterDechunker implements RustOpaqueInterface {}

class DecoderStatus {
  final double progress;
  final PassportMessage? payload;

  const DecoderStatus({
    required this.progress,
    this.payload,
  });

  @override
  int get hashCode => progress.hashCode ^ payload.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DecoderStatus &&
          runtimeType == other.runtimeType &&
          progress == other.progress &&
          payload == other.payload;
}
