// SPDX-FileCopyrightText: 2022 Foundation Devices Inc.
//
// SPDX-License-Identifier: GPL-3.0-or-later

class AllowedCountries {
  static bool isRegionAllowed(String country, String region) {
    if (allowedCountriesWithRegions.containsKey(country)) {
      List<String> regions = allowedCountriesWithRegions[country]!;

      // If the list of regions is empty, all regions from the country are allowed
      if (regions.contains('')) {
        return true;
      }

      // Check if the specified region is in the list
      return regions.contains(region);
    }
    return false;
  }

  static final Map<String, List<String>> allowedCountriesWithRegions = {
    'Albania': [''],
    'Andorra': [''],
    'Angola': [''],
    'Antigua & Barbuda': [''],
    'Argentina': [''],
    'Australia': [''],
    'Austria': [''],
    'Belgium': [''],
    'Belize': [''],
    'Bermuda': [''],
    'Bhutan': [''],
    'Bonaire, St. Estatius & Saba': [''],
    'Bosnia & Herzegovina': [''],
    'Botswana': [''],
    'Brazil': [''],
    'Brunei': [''],
    'Bulgaria': [''],
    'Canada': [''],
    'Cape Verde': [''],
    'Chad': [''],
    'Chile': [''],
    'Christmas Island': [''],
    'Cocos (Keeling) Islands': [''],
    'Colombia': [''],
    'Comoros': [''],
    'Congo': [''],
    'Cook Islands': [''],
    'Costa Rica': [''],
    'Croatia': [''],
    'Cyprus': [''],
    'Czech Republic': [''],
    'Denmark': [''],
    'Djibouti': [''],
    'Dominica': [''],
    'Dominican Republic': [''],
    'El Salvador': [''],
    'Equatorial Guinea': [''],
    'Estonia': [''],
    'Swaziland': [''],
    'Ethiopia': [''],
    'Falkland Islands (Malvinas)': [''],
    'Faroe Islands': [''],
    'Micronesia': [''],
    'Finland': [''],
    'France': [''],
    'French Guyana': [''],
    'French Polynesia': [''],
    'Gambia': [''],
    'Georgia': [''],
    'Germany': [''],
    'Ghana': [''],
    'Gibraltar': [''],
    'Greece': [''],
    'Greenland': [''],
    'Grenada': [''],
    'Guadeloupe': [''],
    'Guam': [''],
    'Guatemala': [''],
    'Guernsey': [''],
    'Guinea': [''],
    'Honduras': [''],
    'Hong Kong': [''],
    'Hungary': [''],
    'Iceland': [''],
    'India': [''],
    'Ireland': [''],
    'Isle of Man': [''],
    'Israel': [''],
    'Italy': [''],
    'Jersey': [''],
    'Kazakhstan': [''],
    'Kenya': [''],
    'Kiribati': [''],
    'Kuwait': [''],
    'Laos': [''],
    'Latvia': [''],
    'Liechtenstein': [''],
    'Lithuania': [''],
    'Luxembourg': [''],
    'Macedonia': [''],
    'Madagascar': [''],
    'Malawi': [''],
    'Malaysia': [''],
    'Malta': [''],
    'Marshall Islands': [''],
    'Martinique': [''],
    'Mauritania': [''],
    'Mayotte': [''],
    'Mexico': [''],
    'Moldova': [''],
    'Monaco': [''],
    'Montenegro': [''],
    'Mozambique': [''],
    'Nauru': [''],
    'Netherlands': [''],
    'New Caledonia': [''],
    'New Zealand': [''],
    'Niue': [''],
    'Norfolk Island': [''],
    'Northern Mariana Islands': [''],
    'Norway': [''],
    'Papua New Guinea': [''],
    'Paraguay': [''],
    'Peru': [''],
    'Philippines': [''],
    'Poland': [''],
    'Portugal': [''],
    'Réunion': [''],
    'Romania': [''],
    'Rwanda': [''],
    'Saint Barthélemy': [''],
    'St. Helena': [''],
    'Saint Lucia': [''],
    'St. Martin (France)': [''],
    'St. Pierre & Miquelon': [''],
    'St. Vincent & Grenadines': [''],
    'San Marino': [''],
    'Sao Tome & Principe': [''],
    'Serbia': [''],
    'Sierra Leone': [''],
    'Singapore': [''],
    'Sint Maarten (Netherlands)': [''],
    'Slovakia': [''],
    'Slovenia': [''],
    'Solomon Islands': [''],
    'South Africa': [''],
    'Spain': [''],
    'Sri Lanka': [''],
    'Suriname': [''],
    'Sweden': [''],
    'Switzerland': [''],
    'Thailand': [''],
    'East Timor': [''],
    'Togo': [''],
    'Tokelau': [''],
    'Tonga': [''],
    'Turkey': [''],
    'Turkmenistan': [''],
    'Turks & Caicos Islands': [''],
    'Tuvalu': [''],
    'Ukraine': [''],
    'United Arab Emirates': [''],
    'United States': [
      'Arizona',
      'Arkansas',
      'California',
      'Colorado',
      'Connecticut',
      'Delaware',
      'Washington',
      'Georgia',
      'Idaho',
      'Illinois',
      'Indiana',
      'Iowa',
      'Kansas',
      'Maine',
      'Massachusetts',
      'Michigan',
      'Minnesota',
      'Mississippi',
      'Missouri',
      'Montana',
      'Nebraska',
      'New Hampshire',
      'North Carolina',
      'North Dakota',
      'Oklahoma',
      'Pennsylvania',
      'Rhode Island',
      'South Carolina',
      'South Dakota',
      'Tennessee',
      'Texas',
      'Utah',
      'Virginia',
      'West Virginia',
      'Wisconsin',
      'Wyoming'
    ],
    'Uruguay': [''],
    'Uzbekistan': [''],
    'Vatican City': [''],
    'Wallis & Futuna Islands': [''],
    'Zambia': ['']
  };
}
