# SPDX-FileCopyrightText: 2024 Foundation Devices Inc.
#
# SPDX-License-Identifier: GPL-3.0-or-later

include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - 'lib/src/generated*'

  plugins:
    - custom_lint
