# SPDX-FileCopyrightText: 2022 Foundation Devices Inc.
#
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "http-ffi"
version = "0.1.0"
authors = ["Igor Cota <igor@foundationdevices.com>"]
edition = "2018"

[lib]
name = "http_ffi"
crate-type = ["cdylib", "staticlib"]

[dependencies]
reqwest = { version = "0.11.10", features = ["socks", "blocking"] }
tokio = { version = "1", features = ["full"] }
lazy_static = "1.4"
log = "0.4.14"
allo-isolate = "0.1.12"

[build-dependencies]
cbindgen = "= 0.24.3"