name: Bug Report
description: Create a report to help us improve Envoy
labels: bug

body:
  - type: dropdown
    id: platform
    attributes:
      label: What mobile OS are you using?
      options:
        - 'iOS'
        - 'Android'
    validations:
      required: true

  - type: textarea
    id: device-details
    attributes:
      label: Please provide details on the device you experienced the bug on
      placeholder: |
        iOS:

        Device: [e.g., iPhone X, iPhone 14, iPad Pro]
        iOS Version: [e.g., iOS 17.1]
        Android:

        Device: [e.g., Google Pixel 8, Samsung Galaxy S21]
        Android Version: [e.g., Android 13] 

  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: |
        Current Behavior: [Describe the issue you are experiencing in detail. Include any error messages or unexpected behavior you encountered.]

        Expected Behavior: [Describe what you expected to happen when using the app.]
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Please provide the steps that you've used to reproduce the issue
      placeholder: |
        1. [First Step]
        2. [Second Step]
        3. [Third Step]
        4. [Additional Steps, if necessary]

  - type: textarea
    id: files
    attributes:
      label: If applicable, add screenshots or screen recordings to help explain the issue.

  - type: textarea
    id: logs
    attributes:
      label: If applicable, add logs to help us diagnose the issue.
      placeholder: To share your logs, head to Settings > Advanced > View Envoy Logs. From here you can save the logs as a file and add to the issue.

  - type: textarea
    id: other
    attributes:
      label: Anything else?
      placeholder: Add any other relevant information here, such as if Tor was in use, network conditions, etc.

  - type: dropdown
    id: impact
    attributes:
      label: Impact of the issue
      description: Please select only one.
      options:
        - label: "Low: Minor issue with minimal impact on usability."
        - label: "Medium: Moderate issue affecting usability."
        - label: "High: Major issue severely impacting usability or app stability."
      multiple: false

  - type: input
    id: related-issues
    attributes:
      label: If you found any similar or related issues, provide links to them here.
    validations:
      required: true