blank_issues_enabled: false
contact_links:
  - name: Security issue disclosure
    url: https://foundation.xyz/security/
    about: Report a security issue with Envoy
  - name: Support Request
    url: https://foundation.xyz/2021/12/support-where-and-when-you-need-it/
    about: Questions and requests for support