// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../third_party/ngwallet.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

Future<NgWallet> getWallet() => RustLib.instance.api.crateApiSimpleGetWallet();

Future<String> nextAddress({required NgWallet wallet}) =>
    RustLib.instance.api.crateApiSimpleNextAddress(wallet: wallet);
