# SPDX-FileCopyrightText: 2022 Foundation Devices Inc.
#
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "ur-ffi"
version = "0.1.0"
authors = ["Igor Cota <igor@foundationdevices.com>"]
edition = "2021"

[lib]
name = "ur_ffi"
crate-type = ["cdylib", "staticlib"]

[dependencies]
log ="0.4.14"
foundation-ur = { git = "https://github.com/Foundation-Devices/foundation-rs", rev = "28dc6f45e89d683ad19f799c3145fe1c575a79d7" }

[dependencies.getrandom]
version = "0.2.3"
features = ["js"]

[build-dependencies]
cbindgen = "= 0.24.3"
