# SPDX-FileCopyrightText: 2022 Foundation Devices Inc.
#
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "ur-ffi"
version = "0.1.0"
authors = ["Igor Cota <igor@foundation.xyz>"]
edition = "2021"

[lib]
name = "ur_ffi"
crate-type = ["cdylib", "staticlib"]

[dependencies]
log ="0.4.14"
foundation-ur = "0.4.0"

[dependencies.getrandom]
version = "0.2.3"
features = ["js"]

[build-dependencies]
cbindgen = "= 0.24.3"
