[package]
name = "rust_lib_ngwallet"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.9.0"
ngwallet = { path = "../../../../ngwallet", features = ["envoy"] }
bdk_wallet = { version = "1.1.0", features = ["rusqlite"] }
# TODO: Check if this is necessary for the iOS build.
#aws-lc-sys = { version = "0.26.0", features = ["bindgen"] }
anyhow = "1.0.97"
log = "0.4.26"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }
