# SPDX-FileCopyrightText: 2025 Foundation Devices Inc.
#
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "rust_lib_ngwallet"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.9.0"

#ngwallet = { path = "../../../../ngwallet", features = ["envoy"] }
ngwallet = {  git = "https://github.com/Foundation-Devices/ngwallet", rev = "2b73e7fb112239b6eabc496936bb2f7d719c7148", features = ["envoy"] }

bdk_wallet = { version = "1.1.0", features = ["rusqlite"] }
bip39 = { version = "2.1.0", features = ["rand"] }
# TODO: Check if this is necessary for the iOS build.
#aws-lc-sys = { version = "0.26.0", features = ["bindgen"] }
anyhow = "1.0.97"
log = "0.4.26"
sled = { version = "0.34" }
chrono = "0.4.40"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }
