// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.8.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

// These functions are ignored because they are not marked as `pub`: `get_uart_characteristic`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `benchmark`, `connect`, `disconnect`, `id`, `is_connected`, `name`, `new`, `read`, `write`

UuidValue get writeCharacteristicUuid =>
    RustLib.instance.api.crateApiBlePeripheralWriteCharacteristicUuid();

BigInt get appMtu => RustLib.instance.api.crateApiBlePeripheralAppMtu();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Peripheral>>
abstract class Peripheral implements RustOpaqueInterface {}
