# SPDX-FileCopyrightText: 2022 Foundation Devices Inc.
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: BeefBench
on: [ workflow_dispatch ]

jobs:
  beef-bench:
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: extractions/setup-just@v1
      - uses: actions/checkout@v2
      - run: just docker-beef

      - uses: actions/upload-artifact@v2
        with:
          name: envoy-screenshot
          path: release/screenshot.png
