# SPDX-FileCopyrightText: 2022 Foundation Devices Inc.
#
# SPDX-License-Identifier: GPL-3.0-or-later
name: QA on simulator

on:
  pull_request:
    branches: [ main ]

jobs:
  android:
    runs-on: ubuntu-latest  # or any other Linux-based runner
    strategy:
      matrix:
        api-level:
          - 29
          # You can add more API levels if you want to run your tests on different APIs.
      fail-fast: true
    steps:
      - uses: actions/checkout@v3
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.19.5'
      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Run flutter doctor
        run: flutter doctor -v

      - name: List connected devices
        run: flutter devices
      - name: Run integration tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          profile: Nexus 6
          script: flutter test integration_test/onboarding_flow_test.dart --verbose
